on: push
name: CI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - uses: s-weigand/setup-conda@v1
    - uses: actions/checkout@v4
      with:
        repository: pytorch/executorch
        path: executorch
        submodules: recursive
    - name: Cached build
      uses: actions/cache@v2
      with:
        path: executorch/cmake-out
        key: ${{ runner.os }}-cmake-${{ hashFiles('executorch/CMakeLists.txt') }}
    - name: Build executorch
      run: |
        cd executorch
        PYTHON_EXECUTABLE=python \
        CMAKE_ARGS="-DEXECUTORCH_BUILD_XNNPACK=ON" \
        ./.ci/scripts/setup-linux.sh cmake
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: yarn build --CDCMAKE_PREFIX_PATH=executorch/cmake-out --CDEXECUTORCH_ROOT=executorch
    - name: Run tests
      run: yarn test
